name: Linting - React Example

on: [ create, push, pull_request ]

defaults:
  run:
    working-directory: ./examples/react-example-webapp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint